apiVersion: "v1"
kind: Pod
metadata:
  name: web
  labels:
    name: web
    app: demo
spec:
  containers:
    - name: python
      image: akhilraaj13/py-red-sql
      env:       
        - name: "pythonread"
          value: "localhost"
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP 